### ISSUE TITLE
Train.py跑不通呀

### ISSUE THREAD

**Issue by liutangming** [huapohen/general_parking_slot_detection#12]
大佬，Train.py跑不通呀，能否更新一版

**Comment by liutangming** [comment]
2023-10-12 12:37:39 root Output and logs will be saved to default/train.log
2023-10-12 12:37:41 root 
                ==============================
                Input  shape: (1, 384, 128)
                Output shape: (8, 12, 4)
                Flops: 6936.9 M
                Params: 49.2 M
                ==============================
2023-10-12 12:37:41 root Loading the train datasets from /home/lto5sgh/2023-parking-slots/seoul
2023-10-12 12:37:41 dataset.data_loader Dataset type: basic, transform type: basic
2023-10-12 12:37:41 root Starting training for 1001 epoch(s)
2023-10-12 12:37:42 root Saved latest checkpoint to: default/yolox_single_scale_model_latest.pth
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    train_and_evaluate(manager)
  File "train.py", line 141, in train_and_evaluate
    train(manager)
  File "train.py", line 109, in train
    manager.logger.info(print_str)
UnboundLocalError: local variable 'print_str' referenced before assignment
